### ISSUE TITLE
Unable to get Main novel list

### ISSUE THREAD

**Issue by Bakaderedere** [calvinaquino/LNReader-Android#253]
I refreshed it lot many time but still it shows error and i have the latest version

**Comment by sid448** [comment]
Even I am also facing the same issue

**Comment by Nandaka** [comment]
Are you using older Android version (below 4.x)? If yes, then it is because the OS doesn't support the new https crypto used by baka tsuki server

**Comment by sid448** [comment]
No I am using Android 5.1x , another weird thing what is happening if I am
accessing baka Tsuki through web also then its showing host is not active
and shows me an earlier version of baka Tsuki .

**Comment by Bakaderedere** [comment]
Same with me. My phone has 5.0.2 version of android.

**Comment by sid448** [comment]
Just a question are you based in India ?
Have govt blocked baka Tsuki?

On 25-Sep-2016 7:14 pm, "Bakaderedere" <notifications@github.com> wrote:

Same with me. My phone has 5.0.2 version of android.

—
You are receiving this because you commented.
Reply to this email directly, view it on GitHub
<https://github.com/calvinaquino/LNReader-Android/issues/253#issuecomment-249422587>,
or mute the thread

**Comment by Bakaderedere** [comment]
Yes. I am indian and the govt hasnt blocked bakatsuki

**Comment by sid448** [comment]
Okay even I am Indian , I am trying to acess it through web but unable to
do so

**Comment by Bakaderedere** [comment]
The site is displayed offline

**Comment by sid448** [comment]
Everything was working fined till 22th Sep

**Comment by Nandaka** [comment]
if you cannot access the site from the phone, then I cannot do anything.

Try to use vpn?

**Comment by sid448** [comment]
Problem resolved its fixed by itself .
Thank You so much for all your help .
