### ISSUE TITLE
Error when trying to load a novel

### ISSUE THREAD

**Issue by Ririio** [calvinaquino/LNReader-Android#270]
I found a novel that I wanted to read in your app, but when I tried to open it, it gives me an error. I tried  reinstalling the app, but it doesn't seem to work. I also tried to enable quick load novel list, but it doesnt
work.
![capture _2017-10-06-12-28-03](https://user-images.githubusercontent.com/32577022/31288261-247c51ce-aa92-11e7-82b4-860fee4faddc.png)

**Comment by Nandaka** [comment]
what is your android version? can you open baka tsuki website in the browser without throwing error?

Most likely your android version doesn't have the root certificate that BakaTsuki use. Try to enable ```Load App Keystore``` in Settings --> Update & Notification on Network section.

**Comment by OtakuPlayer** [comment]
Also me it shows me:
"Class
Javax.net.ssl.SSLHandShakeException:
java.security.cert.CertPathValidatorException:
Trust anchor for certification path not found."
Even though i already did enabling the thing that you said. Btw ny android version is 7.1.1

**Comment by Nandaka** [comment]
weird, can you open the website in your phone browser? There is a maintenance recenty in bakatsuki website

**Comment by OtakuPlayer** [comment]
Can you send me a link to the website?

**Comment by Nandaka** [comment]
https://www.baka-tsuki.org/project/index.php?title=Main_Page

**Comment by OtakuPlayer** [comment]
I think I can cause I did enter the site but it also showed me this :

**Comment by Nandaka** [comment]
The image doesn't load...

**Comment by Nandaka** [comment]
btw, what is your phone? usually this is because the root certificate in your phone is not updated.

This is what the certificate chain used by the site
![image](https://user-images.githubusercontent.com/836867/33070421-ebfb4b04-cef2-11e7-9f52-e6dfc5ea70e9.png)

If you check your phone Trusted Credentials, it should show "Comodo ECC Certification Authority" as part of the System Credentials

**Comment by OtakuPlayer** [comment]
My phone is Asu_X00ID

**Comment by OtakuPlayer** [comment]
It does say that but its still wont let me read anything should I
re-download it again?

**Comment by Nandaka** [comment]
> I think I can cause I did enter the site but it also showed me this :

I cannot see the images. IF it says https certificate warning, most likely the system doesn't have the root certificate installed. Try to update your phone?

**Comment by OtakuPlayer** [comment]
The image is just a blank screen with this :
"Class
Javax.net.ssl.SSLHandShakeException:
java.security.cert.CertPathValidatorException:
Trust anchor for certification path not found."

**Comment by Nandaka** [comment]
that is in your android browser? then your phone doesn't have the certificate from the new server. I'll see if I can create a settings to ignore the ssl warning.

**Comment by OtakuPlayer** [comment]
The errror thing was in the app so like I cant read the novels and I
checked the trust certificates and I have everything on. If only i can send
you a pic to show you what I mean

**Comment by OtakuPlayer** [comment]
For now I deleted the app

**Comment by Nandaka** [comment]
Can you try the beta release below? I have updated the keystore to reflect what the server uses.
[release-1.1.50-beta1.zip](https://github.com/calvinaquino/LNReader-Android/files/1494646/release-1.1.50-beta1.zip)

If it doesn't work, I'll add an option to ignore SSL error.

**Comment by OtakuPlayer** [comment]
YESSSSSSS!!!!!! Thank you so much!!! It finally worked. I hope you can
continue fixing problems like these. Thank you so much

**Comment by OtakuPlayer** [comment]
I got one more thing to ask how do you read the Date A Live novel in
english cause the one I found was in polish so I couldn't understand .

On Nov 22, 2017 12:46 PM, "Nandaka" <notifications@github.com> wrote:

Can you try the beta release below? I have updated the keystore to reflect
what the server uses.
release-1.1.50-beta1.zip
<https://github.com/calvinaquino/LNReader-Android/files/1494646/release-1.1.50-beta1.zip>

If it doesn't work, I'll add an option to ignore SSL error.

—
You are receiving this because you commented.
Reply to this email directly, view it on GitHub
<https://github.com/calvinaquino/LNReader-Android/issues/270#issuecomment-346242298>,
or mute the thread

**Comment by Nandaka** [comment]
It is not possible as the novel is not available anymore in BakaTsuki (got DMCA-ed)

https://www.baka-tsuki.org/project/index.php?title=Date_A_Live

**Comment by OtakuPlayer** [comment]
So is it completely hopeless to read Date A Live again cause I really want
to continue reading it

**Comment by otakufever** [comment]
Thank you for the beta release...I have the same problem too so I search for a resolution...thank you very much...

**Comment by Nandaka** [comment]
Ok, I will push to the official google play release as non-beta.
