### ISSUE TITLE
Security Exception

### ISSUE THREAD

**Issue by shikaya** [calvinaquino/LNReader-Android#274]
Hey great App you created! Since a month now I cant properly use it sadly since im always getting an Exception. I read about the tip with the Load App Keystore in the Forums and tried it , currently it is working ... what are the drawbacks of it? And also could be the reason for it my Android version 4.2.2? I read that this Version didnt have Keystores yet.

Greets Shikaya

**Comment by Nandaka** [comment]
Hiya,

You got the Security Exception because the Root Certificate in your phone is missing/not updated by the vendor, so when the application tried to validate the SSL Certificate path, it will failed due to no root certificate to check.

By using App Keystore, the application will use the embedded root certificate to validate the SSL certification path.

The drawback, if for whatever reason BakaTsuki choose to change the SSL Certificate again (e.g. moving server), then I need to publish new release with the update certificate.

Consider changing your phone or try to install custom rom with latest android version/security patch.

**Comment by epona999** [comment]
so I am having this same issue since and I can't afford a new phone atm(my phone is only about a year and a half old so I'm not sure why this is a problem) so I was wondering about what you mean by loading app keystore, is that an app I can download?

**Comment by Nandaka** [comment]
In the apps, go to Settings -> Update and Notification -> Load App Keystore is tick/enabled.

Ensure you are using the latest version (as per current is 1.1.50).

**Comment by FinderX** [comment]
Hi. Respect to version, google play store only show the 1.1.46 version...

**Comment by Nandaka** [comment]
I assume you are using older android version?

Android below version 3 is not supported anymore.

**Comment by FinderX** [comment]
Using Android 7.1.2.
Here is a screenshot for the google play store.
![screenshot from 2018-01-17 14-40-08](https://user-images.githubusercontent.com/8683793/35057784-c434d512-fb94-11e7-93c6-951b9116161e.png)

Or the version 1.1.50 has another name than BakaReader EX ?

**Comment by Nandaka** [comment]
Updated the rollout %, it should show only 1.1.50 now, or else you can get the apk from https://github.com/calvinaquino/LNReader-Android/releases

**Comment by FinderX** [comment]
Great! Is working!
The app update automatically and now the novel are downloading right now.
Thank you very much.
